//
//  GameSession.swift
//  TypeBattle
//
//  Created by Fernando Jinzenji on 2017-07-12.
//  Copyright © 2017 Jimmy Hoang. All rights reserved.
//

import Foundation

enum GameSessionStatus {
    case waitingForPlayers
    case started
    case finished
}

class GameSession {

    var gameSessionID: String //ID generated by Firebase
    var name: String
    var gameText: String
    var capacity: Int
    var players: [PlayerSession]
    var status: GameSessionStatus
    
    init(name: String, gameText: String, capacity: Int) {
        self.gameSessionID = ""
        self.name = name
        self.gameText = gameText
        self.capacity = capacity
        self.players = [PlayerSession]()
        self.status = .waitingForPlayers
    }
    
    func saveToFirebase() {
        //TODO: persist to firebase and get id
        
    }
    
    func startGameSession() {
        
        self.status = .started
        
    }
    
    func finishGameSession() {
        
        self.status = .finished
        
    }
}
