//
//  Player.swift
//  TypeBattle
//
//  Created by Jimmy Hoang on 2017-07-12.
//  Copyright © 2017 Jimmy Hoang. All rights reserved.
//

import Foundation
import UIKit

class Player {
    
    // Profile properties
    var playerID: String //ID generated by Firebase
    var name: String
    var email: String
    var password: String
    
    // Additional profile properties
    var avatar: UIImage = UIImage()
    
    // Game/stats properties
    var level = 0
    var levelProgression = 0.0
    var matchsWon = 0
    var matchsPlayed = 0
    
    init(name: String, email: String, password: String) {
        self.playerID = ""
        self.name = name
        self.email = email
        self.password = password
    }
    
    func saveToFirebase() {
        
        //TODO: save player to firebase and get the id
        
    }
    
    func login() {}
    
    func logout() {}
    
    func changeAvatar() {}
        
    //    var name:String
    //    var uniqueIdentifier:String
    //    var avatar:UIImage
    //    var level:Int
    //    var experience:Double?
    //    var matchesWon:Int?
    //    var matchesPlayed:Int?
    //    var fastestGame:Int?
    //    var perk:String?
    //    var timeFinished:Int?
    //
    //    init(name:String,uniqueIdentifier:String,avatar:UIImage,level:Int) {
    //        self.name             = name
    //        self.uniqueIdentifier = uniqueIdentifier
    //        self.avatar           = avatar
    //        self.level            = level
    //    }
}
